In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("../data/health_finance.csv")

In [8]:
df.head()

,patient_id,age,gender,bmi,smoking_status,alcohol_use,diabetes,hypertension,heart_disease,cholesterol,...,hospital_revenue,hospital_expense,hospital_credit_score,pharma_stock_return,pharma_volatility,esg_score,investment_risk,portfolio_return,overall_health_risk,financial_risk_score
0,1,58,Male,24.60,Non-Smoker,No,1,0,0,301.23,...,5636673.96,3737763.70,677,25.17,40.95,75.53,High,30.95,Low,44.15
1,2,47,Male,21.86,Non-Smoker,No,0,0,0,242.76,...,4571958.99,4051833.16,617,6.75,39.06,75.93,Medium,9.73,Low,29.69
2,3,61,Male,29.51,Non-Smoker,Yes,1,1,1,329.49,...,4232347.29,3247645.55,651,24.45,47.03,88.63,High,34.57,High,100.00
3,4,77,Male,18.47,Smoker,No,0,1,1,268.13,...,3879418.67,2890253.41,693,45.10,12.95,68.75,Low,53.65,High,45.63
4,5,45,Female,25.66,Non-Smoker,No,0,0,0,300.29,...,4579692.52,3025125.97,675,7.53,45.72,73.76,High,13.28,Low,55.92

In [9]:
df.shape

(9992, 40)

In [ ]:
df.sample(7) # 7 random samples

,patient_id,age,gender,bmi,smoking_status,alcohol_use,diabetes,hypertension,heart_disease,cholesterol,...,hospital_revenue,hospital_expense,hospital_credit_score,pharma_stock_return,pharma_volatility,esg_score,investment_risk,portfolio_return,overall_health_risk,financial_risk_score
9718,9719,60,Female,35.56,Non-Smoker,No,1,1,1,300.91,...,4604272.65,3547318.46,644,28.23,43.53,67.86,High,31.31,High,100.00
999,1000,60,Male,40.36,Non-Smoker,No,1,1,1,316.64,...,3453766.05,2923822.89,628,15.30,55.48,84.22,High,25.75,High,96.92
7264,7265,47,Male,24.25,Non-Smoker,No,0,0,0,273.78,...,4082506.78,2688859.82,656,38.20,32.30,61.79,Medium,41.89,Low,26.84
3896,3897,75,Female,32.00,Non-Smoker,Yes,1,1,1,292.80,...,5125846.08,3849995.17,650,58.31,14.68,81.86,Low,69.13,High,100.00
9597,9598,49,Female,22.53,Non-Smoker,Yes,0,0,0,225.44,...,2914004.66,2265501.46,653,26.79,32.73,61.99,Medium,36.31,Low,40.63
9638,9639,39,Female,16.55,Non-Smoker,No,0,0,0,253.58,...,6535978.87,4560742.68,663,7.44,9.18,64.02,Low,22.62,Low,12.67
4719,4720,52,Male,37.67,Non-Smoker,No,0,1,0,269.38,...,3635743.96,2481715.89,689,16.31,55.50,76.67,High,23.70,Low,87.48

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9992 entries, 0 to 9991
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   patient_id              9992 non-null   int64
 1   age                     9992 non-null   int64
 2   gender                  9992 non-null   object
 3   bmi                     9792 non-null   float64
 4   smoking_status          9992 non-null   object
 5   alcohol_use             9992 non-null   object
 6   diabetes                9992 non-null   int64
 7   hypertension            9992 non-null   int64
 8   heart_disease           9992 non-null   int64
 9   cholesterol             9792 non-null   float64
 10  glucose                 9792 non-null   float64
 11  systolic_bp             9992 non-null   float64
 12  diastolic_bp            9992 non-null   float64
 13  heart_rate              9992 non-null   int64
 14  oxygen_saturation       9992 non-null   float64
 15  hospital_visits         9992 non-null   int64
 16  icu_admission           9992 non-null   int64
 17  length_of_stay          9992 non-null   int64
 18  readmission             9992 non-null   int64
 19  mortality_risk          9992 non-null   object
 20  disease_outbreak_index  9992 non-null   float64
 21  treatment_type          9992 non-null   object
 22  drug_name               9992 non-null   object
 23  drug_efficacy           9792 non-null   float64
 24  side_effect_score       9992 non-null   float64
 25  insurance_plan          9992 non-null   object
 26  annual_premium          9992 non-null   float64
 27  claim_amount            9792 non-null   float64
 28  claim_frequency         9992 non-null   int64
 29  fraud_risk              9992 non-null   object
 30  hospital_revenue        9992 non-null   float64
 31  hospital_expense        9992 non-null   float64
 32  hospital_credit_score   9992 non-null   int64
 33  pharma_stock_return     9992 non-null   float64
 34  pharma_volatility       9992 non-null   float64
 35  esg_score               9992 non-null   float64
 36  investment_risk         9992 non-null   object
 37  portfolio_return        9992 non-null   float64
 38  overall_health_risk     9992 non-null   object
 39  financial_risk_score    9992 non-null   float64
dtypes: float64(18), int64(12), object(10)
memory usage: 3.0+ MB
None

In [14]:
print(df.isnull().sum())

patient_id                  0
age                         0
gender                      0
bmi                       200
smoking_status              0
alcohol_use                 0
diabetes                    0
hypertension                0
heart_disease               0
cholesterol               200
glucose                   200
systolic_bp                 0
diastolic_bp                0
heart_rate                  0
oxygen_saturation           0
hospital_visits             0
icu_admission               0
length_of_stay              0
readmission                 0
mortality_risk              0
disease_outbreak_index      0
treatment_type              0
drug_name                   0
drug_efficacy             200
side_effect_score           0
insurance_plan              0
annual_premium              0
claim_amount              200
claim_frequency             0
fraud_risk                  0
hospital_revenue            0
hospital_expense            0
hospital_credit_score       0
pharma_stock_return         0
pharma_volatility           0
esg_score                   0
investment_risk             0
portfolio_return            0
overall_health_risk         0
financial_risk_score        0
dtype: int64

In [15]:
print((df.isnull().sum()/len(df))*100)

patient_id                0.000000
age                       0.000000
gender                    0.000000
bmi                       2.001601
smoking_status            0.000000
alcohol_use               0.000000
diabetes                  0.000000
hypertension              0.000000
heart_disease             0.000000
cholesterol               2.001601
glucose                   2.001601
systolic_bp               0.000000
diastolic_bp              0.000000
heart_rate                0.000000
oxygen_saturation         0.000000
hospital_visits           0.000000
icu_admission             0.000000
length_of_stay            0.000000
readmission               0.000000
mortality_risk            0.000000
disease_outbreak_index    0.000000
treatment_type            0.000000
drug_name                 0.000000
drug_efficacy             2.001601
side_effect_score         0.000000
insurance_plan            0.000000
annual_premium            0.000000
claim_amount              2.001601
claim_frequency           0.000000
fraud_risk                0.000000
hospital_revenue          0.000000
hospital_expense          0.000000
hospital_credit_score     0.000000
pharma_stock_return       0.000000
pharma_volatility         0.000000
esg_score                 0.000000
investment_risk           0.000000
portfolio_return          0.000000
overall_health_risk       0.000000
financial_risk_score      0.000000
dtype: float64

In [16]:
print(df.duplicated().sum())

0

In [17]:
print(df.describe())

        patient_id          age          bmi     diabetes  hypertension  \
count  9992.000000  9992.000000  9792.000000  9992.000000   9992.000000
mean   4996.500000    49.679043    27.306509     0.222978      0.343475
std    2884.586279    17.200280     5.432937     0.416265      0.474892
min       1.000000    18.000000    15.000000     0.000000      0.000000
25%    2498.750000    37.000000    23.640000     0.000000      0.000000
50%    4996.500000    49.000000    27.120000     0.000000      0.000000
75%    7494.250000    62.000000    30.630000     0.000000      1.000000
max    9992.000000    90.000000    61.450000     1.000000      1.000000

       heart_disease  cholesterol      glucose  systolic_bp  diastolic_bp  \
count    9992.000000  9792.000000  9792.000000  9992.000000   9992.000000
mean        0.240793   268.647518   119.089200   133.596220     81.697350
std         0.427586    47.230217    29.150338    15.850755      7.711245
min         0.000000   167.540000    68.800000    91.950000     54.300000
25%         0.000000   243.207500   101.167500   121.570000     76.150000
50%         0.000000   262.740000   110.210000   131.800000     81.200000
75%         0.000000   284.757500   128.477500   145.602500     87.080000
max         1.000000   663.670000   351.840000   188.710000    109.530000

       ...   claim_amount  claim_frequency  hospital_revenue  \
count  ...    9792.000000      9992.000000      9.992000e+03
mean   ...   10926.081810         2.059147      5.115987e+06
std    ...   12185.027018         1.430261      1.451458e+06
min    ...       0.000000         0.000000      1.000000e+06
25%    ...    4456.665000         1.000000      4.345795e+06
50%    ...    6601.725000         2.000000      5.013765e+06
75%    ...   12044.420000         3.000000      5.709200e+06
max    ...  188966.800000         8.000000      2.357152e+07

       hospital_expense  hospital_credit_score  pharma_stock_return  \
count      9.992000e+03            9992.000000          9992.000000
mean       4.096139e+06             649.515312            13.009109
std        1.256766e+06              26.575093            21.636449
min        6.907405e+05             556.000000          -142.370000
25%        3.373943e+06             630.000000            -0.400000
50%        3.982467e+06             649.000000            12.300000
75%        4.634504e+06             669.000000            24.922500
max        2.041027e+07             733.000000           263.810000

       pharma_volatility    esg_score  portfolio_return  financial_risk_score
count        9992.000000  9992.000000       9992.000000           9992.000000
mean           32.612402    75.077361         21.041180             49.287421
std            15.762158     9.828168         21.923345             27.263254
min             5.000000    37.920000       -138.460000              0.000000
25%            19.017500    68.507500          7.407500             28.530000
50%            32.800000    75.185000         20.430000             47.075000
75%            46.180000    81.690000         33.140000             68.122500
max            59.990000   100.000000        270.450000            100.000000

[8 rows x 30 columns]